kmod_autodetect_input = true
keyboard_key_threshold = 25

[imports.build_enum]
"ugrd.kmod.input" = [ "autodetect_input" ]

[import_order.after]
"autodetect_input" = "get_kernel_version"

[custom_parameters]
kmod_autodetect_input = "bool"  # Whether or not to detect input devices
keyboard_key_threshold = "int"  # Number of keys on a keyboard device to be detected as a keyboard
