modules = [ "ugrd.base.core",
	    "ugrd.fs.mounts",
	    "ugrd.base.cmdline",
	    "ugrd.base.banner",
	    "ugrd.kmod.kmod",
	    "ugrd.fs.cpio",
	    "ugrd.base.checks" ]

binaries = [ "awk", "bc", "dd", "grep", "ls", "cp", "cat", "stty", "switch_root", "rm" ]

paths = [ "root", "tmp" ]

loglevel = 5
shebang_args = "-l"
autodetect_init = true

[imports.config_processing]
"ugrd.base.base" = [ "_process_loglevel", "_process_init_target" ]

[imports.build_enum]
"ugrd.base.base" = [ "autodetect_init" ]

[imports.build_tasks]
"ugrd.base.base" = [ "set_shebang", "export_switch_root_target" ]

[imports.build_final]
"ugrd.base.base" = [ "set_init_final_order" ]

[imports.init_pre]
"ugrd.base.base" = [ "set_loglevel" ]

[imports.init_final]
"ugrd.base.base" = [ "do_switch_root" ]

[imports.functions]
"ugrd.base.base" = [ "check_var", "setvar", "readvar", "wait_for_space", "prompt_user", "retry",
                     "klog", "edebug", "einfo", "ewarn", "eerror",
		     "rd_fail", "rd_restart", "_find_init" ]

[imports.checks]
"ugrd.base.base" = [ "check_init_target", "check_switch_root_last" ]

[import_order.after]
set_loglevel = "parse_cmdline"

[custom_parameters]
switch_root_target = "Path"  # Specifies the location of the new root filesystem
init_target = "Path"  # Specifies the location of the system init file
autodetect_init = "bool"  # If set to true, the init_target will be autodetected based on the system's init system
loglevel = "int"  # Set the kernel log level at /proc/sys/kernel/printk
shebang = "str"  # Add the shebang property, shebang_args should be used instead
shebang_args = "str"  # Add the shebang_args property
