# This module generates an initramfs that uses a yubikey to decrypt a luks keyfile.
# The sc_public_key must be specified.
# fat formatted usb storage.
# GPG encrypted keyfiles are on /boot, protected with the yubikey.

modules = [
  "ugrd.kmod.usb",
  "ugrd.crypto.smartcard",
]

# This public key can be anywhere ugrd can read at build time, made with gpg --export
sc_public_key = "/etc/ugrd/pubkey.gpg"

# This is necessary if the keyfile is on another device.
# The keyfile could be added as a dependency. if it's on the same device.
auto_mounts = ['/boot']  # Automatically create mount config for /boot on the host

# Information about the LUKS volume
[cryptsetup.root]
key_type = "gpg"
key_file = "/boot/rootfs.luks.gpg"
try_nokey = true  # Attempt to unlock with passphrase entry if unable to use the keyfile
